from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, create_engine, text
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from pgvector.sqlalchemy import Vector

from config.config import config
import datetime

Base = declarative_base()

# Embedding dimension for sentence-transformers' all-MiniLM-L6-v2 model.
# If you ever switch embedding models, this MUST match the new model's output
# size exactly, and every existing embedding column needs a migration (you
# can't mix 384-dim and 768-dim vectors in the same column).
EMBEDDING_DIM = 384


class Price(Base):
    """
    Time-series price data.
    Intended to be a TimescaleDB hypertable.
    """
    __tablename__ = 'prices'

    timestamp = Column(DateTime, primary_key=True, index=True)
    ticker = Column(String, primary_key=True, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)


class NewsArticle(Base):
    """
    Normalized news articles from various sources. Articles are short enough
    (headline + description) that we embed the whole thing as one vector --
    unlike filings, they don't need chunking.
    """
    __tablename__ = 'news_articles'

    id = Column(Integer, primary_key=True, autoincrement=True)
    article_id = Column(String, unique=True, nullable=False)  # Provider's unique ID
    ticker = Column(String, index=True, nullable=False)
    title = Column(String, nullable=False)
    content = Column(String)
    embedding = Column(Vector(EMBEDDING_DIM))  # nomic-embed-text dimensions

    source = Column(String, nullable=False)
    published_at = Column(DateTime, index=True)


class SentimentScore(Base):
    """
    Sentiment analysis results for news articles.
    """
    __tablename__ = 'sentiment_scores'

    id = Column(Integer, primary_key=True, autoincrement=True)
    article_id = Column(Integer, ForeignKey('news_articles.id'), nullable=False)
    label = Column(String, nullable=False)  # e.g., positive, neutral, negative
    confidence = Column(Float, nullable=False)
    model_version = Column(String, nullable=False)
    scored_at = Column(DateTime, default=datetime.datetime.utcnow)


class CompanyFiling(Base):
    """
    SEC Filings (10-K, 10-Q) metadata and local paths.

    NOTE: we deliberately do NOT store a single embedding on this table.
    Filings can be hundreds of pages -- one vector for the whole document
    would only ever represent the first ~256-512 tokens the embedding model
    reads before its context limit truncates the rest. Instead, each filing
    is split into chunks stored in FilingChunk (see below), so semantic
    search can return "this specific paragraph about supply chain risk"
    rather than "this entire 10-K is somewhat relevant."
    """
    __tablename__ = 'company_filings'

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String, index=True, nullable=False)
    filing_type = Column(String, nullable=False)  # 10-K, 10-Q
    filed_at = Column(DateTime, index=True)
    local_path = Column(String, nullable=False)
    accession_number = Column(String, unique=True)

    chunks = relationship("FilingChunk", back_populates="filing", cascade="all, delete-orphan")


class FilingChunk(Base):
    """
    One ~350-word chunk of a parent filing, with its own embedding.
    This -- not CompanyFiling -- is what semantic_search_filings() searches.
    """
    __tablename__ = 'filing_chunks'

    id = Column(Integer, primary_key=True, autoincrement=True)
    filing_id = Column(Integer, ForeignKey('company_filings.id'), nullable=False, index=True)
    chunk_index = Column(Integer, nullable=False)
    content = Column(String, nullable=False)
    embedding = Column(Vector(EMBEDDING_DIM))

    filing = relationship("CompanyFiling", back_populates="chunks")


class ResearchReport(Base):
    """
    Final research reports generated by the ResearchAgent.
    """
    __tablename__ = 'research_reports'

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String, index=True, nullable=False)
    report_date = Column(DateTime, default=datetime.datetime.utcnow)
    rating = Column(String)  # e.g., 'Buy', 'Hold', 'Neutral'
    content = Column(String, nullable=False)  # The full markdown report
    model_used = Column(String)  # e.g., 'gemma4:31b'


# Database Engine and Session Setup

def get_engine():
    if config.DATABASE_URL is None:
        # Fallback to in-memory sqlite for testing/local dev if no URL provided
        return create_engine("sqlite:///:memory:")
    return create_engine(config.DATABASE_URL)


engine = get_engine()
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def init_db():
    """
    Initializes the database: enables pgvector, creates tables, and converts
    'prices' to a hypertable.
    """
    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector;"))
        conn.commit()

    Base.metadata.create_all(bind=engine)

    with engine.connect() as conn:
        try:
            conn.execute(text("SELECT create_hypertable('prices', 'timestamp', if_not_exists => TRUE);"))
            conn.commit()
        except Exception as e:
            print(f"Hypertable creation failed or already exists: {e}")


if __name__ == "__main__":
    init_db()
    print("Database initialized successfully.")